/**
 * dsh-evolve package entry: the Cordis plugin plus the pure, reusable core
 * (detector, features, contracts), the offline analyzer, the eval lab, and the
 * v0.2 self-evolution engine (experience / mutation / targets / validation /
 * privacy / commons / security).
 *
 * @module dsh-evolve
 */

export * from './plugin/index.js'
export { analyzeLog, renderReport, collectorEvents } from './offline/analyzer.js'
export { readSessionFile, findSessionArtifact, listSessionArtifacts, parseSessionLog } from './offline/session-reader.js'
export { runTaskOnce, buildLaunchRequest, type Launcher } from './offline/eval/runner.js'
export { runGrader, spawnCommand } from './offline/eval/grader.js'
export { aggregateMetrics, compareArms } from './offline/eval/metrics.js'
export { assessRecovery } from './offline/eval/recovery.js'
export { sweepTriggerScores, renderSweep } from './offline/eval/sweep.js'
export { renderReport as renderEvalReport, buildReportData } from './offline/eval/report.js'
export { buildComparisonReport, readEvalRecords } from './offline/eval/report-merge.js'
export { mineSessionArtifacts } from './offline/analyze/mine-sessions.js'
export { runV02Command, parseFlags } from './offline/commands.js'
export { runOverheadBenchmark, writeOverheadReport, syntheticEvents } from './offline/benchmark.js'

// v0.2 release hardening
export { CircuitBreaker, BreakerRegistry, isRetryableFailure, CircuitOpenError, type BreakerState, type BreakerCapability } from './background/circuit-breaker.js'
export { BackgroundQueue, DEFAULT_QUEUE_OPTIONS, type EvolutionJob, type EvolutionJobKind, type JobPriority } from './background/queue.js'
export { EvolutionWorker, JOB_CAPABILITY } from './background/worker.js'
export { EvolutionScheduler, planJobs, DEFAULT_SCHEDULER_CONFIG, type EvolutionTrigger } from './background/scheduler.js'
export { decideEvolutionAction, EVOLUTION_MODES, type EvolutionMode, type ModeAction } from './permissions/evolution-mode.js'
export { evaluateGate, isNeverAutomatic, permissionSummary, type GateRequest, type GateVerdict } from './permissions/promotion-gate.js'
export { isAllowedUrl, parseHost, defaultNetworkPolicy, NetworkPolicyError, type NetworkPolicy } from './network/allowlist.js'
export { DefaultEvolveNetworkClient, type EvolveNetworkClient, type NetworkAuditEntry } from './network/client.js'
export { DiagnosticLog, type DiagnosticEntry } from './storage/diagnostics.js'
export { runAudit, renderAuditReport, writeAuditReport, runScopeChecks, detectDshVersion } from './audit/report.js'
export { scanPrivileges, auditPrivilege } from './audit/privilege.js'
export { inventoryWriteSites, checkPathTraversal, auditFilesystem } from './audit/filesystem.js'
export { inventoryNetworkSites, auditNetwork } from './audit/network.js'
export { runLifecycleLoop, checkUninstall, auditLifecycle } from './audit/lifecycle.js'
export { runNonInterference, trajectoryMetrics, auditNonInterference } from './audit/non-interference.js'
export { auditFailureIsolation } from './audit/failure-isolation.js'
export { runPrivacyAdversarial, adversarialSessionEvents, auditPrivacy } from './audit/privacy.js'
export { runSupplyChain, auditSupplyChain } from './audit/supply-chain.js'
export { runSkillSecurity, auditSkillSecurity } from './audit/skill-security.js'

// v0.2 core
export * from './contracts/actions.js'
export * from './episode/contracts.js'
export * from './experience/contracts.js'
export * from './mutation/contracts.js'
export { extractEpisodes, episodeId } from './episode/extractor.js'
export { mineEpisode, procedureStepKey, structuralArgsKey } from './experience/miner.js'
export { finalizeCandidate, summarizePayload, payloadKey } from './experience/normalizer.js'
export { mergeCandidates, shouldPromoteToCandidate } from './experience/deduplicator.js'
export { computeConfidence, buildEvidence } from './experience/confidence.js'
export { ExperienceStore } from './experience/store.js'
export { retrieveExperiences, renderTemporaryContext } from './experience/retriever.js'
export { TARGET_RISK, requiredGate, gateForTarget } from './mutation/risk.js'
export { planMutations, draftSkillFromCorrection } from './mutation/planner.js'
export { MutationRegistry } from './mutation/registry.js'
export { MemoryStore } from './targets/memory/store.js'
export { ProfileStore } from './targets/profile/store.js'
export { SkillStore } from './targets/skill/store.js'
export { optimizeFromCorrections, optimizeFromUsage, proposeOptimization } from './targets/skill/optimizer.js'
export { RoutingStore, matchSkill, taskKeywords } from './targets/skill-routing/store.js'
export { RecipeStore } from './targets/recipe/store.js'
export { PolicyStore, RUNTIME_ACTION_RECIPE } from './targets/policy/store.js'
export { applyPromotedMutation } from './targets/applier.js'
export { replaySkillProposal, replayPolicyProposal } from './validation/replay.js'
export { shadowRun, shadowSkillProposal } from './validation/shadow.js'
export { evaluateProposal, regressionCheck } from './validation/evaluator.js'
export { runPromotionFlow } from './validation/promotion.js'
export { scanPii, scanObjectPii } from './privacy/pii-filter.js'
export { scanSecrets, scanObjectSecrets } from './privacy/secret-filter.js'
export { compileExperience, compileMany } from './privacy/compiler.js'
export { capsuleHash, renderCapsulePreview, supportBucket, outcomeDirection } from './privacy/capsule.js'
export { parseManifest, compareReleases, isNewerRelease } from './commons/manifest.js'
export { SyncEngine, shouldSync, assetUrl } from './commons/sync.js'
export { verifyCapsule, sha256 } from './commons/verifier.js'
export { matchCapsules, matchCapsule, compatible } from './commons/matcher.js'
export { prepareContribution, canAutoContribute, DEFAULT_CONTRIBUTION_POLICY } from './commons/contribution.js'
export { validateCapsule, findProhibitedFields, validateFileType } from './security/schema-validator.js'
export { scanSkillInstructions, scanBlocksActivation } from './security/skill-scanner.js'
export { capabilitiesFor, allowsCapability, networkAllowed } from './security/capability-policy.js'
